-- Create dedicated database and schema for real-time telemetry project
CREATE DATABASE IF NOT EXISTS REALTIME_ECOMMERCE_DB;
USE DATABASE REALTIME_ECOMMERCE_DB;

CREATE SCHEMA IF NOT EXISTS TELEMETRY;
USE SCHEMA TELEMETRY;

-- Reference table schema for Lenskart telemetry data
CREATE OR REPLACE TABLE RAW_LENSKART_TELEMETRY (
    ORDER_ID STRING,
    ORDER_DATE TIMESTAMP_NTZ,
    CITY STRING,
    STATE STRING,
    SALES_CHANNEL STRING
);
